name: "Panel Hub"
version: "1.0.8"
slug: "panel_hub"
description: "user rights management for Panels"
arch:
  - amd64
  - aarch64
startup: application
boot: auto
webui: "http://[HOST]:[PORT:8000]"
panel_icon: mdi:shield-account
panel_title: Panel Hub
ingress: true
ingress_port: 8000
ports:
  8000/tcp: 8000
host_network: false
hassio_api: true
homeassistant_api: true
options:
  ha_url: "http://homeassistant.local:8123"
schema:
  ha_url: str
