name: "Panel Hub"
version: "1.0.0"
slug: "panel_hub"
description: "user rights management for Panels"
arch:
  - amd64
  - aarch64
startup: application
boot: auto
panel_icon: mdi:shield-account
panel_title: Panel Hub
ingress: true
ingress_port: 8000
ingress_stream_timeout: 120
hassio_api: true
homeassistant_api: true
map:
  - homeassistant_config:rw
options:
  ha_url: "http://homeassistant.local:8123"
schema:
  ha_url: str
